tasks:
  - name: terraform
    before: |
      source ./bin/install_terraform_cli
      source ./bin/generate_tfrc_credentials
      cp $PROJECT_ROOT/terraform.tfvars.example /$PROJECT_ROOT/terraform.tfvars
  - name: aws-cli
    before: |
      source ./bin/.install_aws_cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
